### ISSUE TITLE
Will need to set page and count in order to get all questions

### ISSUE THREAD

**Issue by dchong1999** [fecgreyjoy/FEC#78]
https://github.com/fecgreyjoy/FEC/blob/5d0cfb6679dacbc1acdcb4dd1e4060bb784dcd9b/client/src/components/Questions/Questions.jsx#L27-L41

#### Description
You are not pulling enough questions upon initial getQuestions

#### Screenshots (if ui based)
Not UI Based

#### Files
Questions.jsx > questions state

#### To Reproduce
N/A

#### Tasks (optional)
Include specific tasks in the order they need to be done in. Include links to specific lines of code where the task should happen at.
- [ ] Will need to pull a large amount of questions at once (i.e. page: 1, count: (number of questions you want) * 20)
- [ ] Then will need to conditionally store the received questions (i.e. keep storing questions until length of stored questions == what you want/need)
- [ ] Repeat as needed (can use similar page/count method to render next 2 questions upon refresh --> i.e. page: 1, count: (number of questions you had + 2) *20))
- [ ] Note: let me know if this was described in a confusing manner, I can show you how I did it in my code to get it to work

**Comment by rocknswimmer** [comment]
hard coded count in sever set to 1000 after the api started working. probs not best practice but wanted a quick pull request when that change was needed. know I should refactor to make more api calls for smaller data chunks but only became aware of that during the recorded lecture on optimization this week.
