### ISSUE TITLE
Minor bug with your image resizing

### ISSUE THREAD

**Issue by p-sturtevant** [fecgreyjoy/FEC#81]
https://github.com/fecgreyjoy/FEC/blob/5d0cfb6679dacbc1acdcb4dd1e4060bb784dcd9b/client/src/components/View/Styled/LargeImage.styled.jsx#L29-L30

###### Description #######
As we discussed, this is not going to contain the whole image. 

####Tasks ####

- [ ] Change background-size to 'contain'
- [ ] Set background-repeat to 'no-repeat'
- [ ] Set background-position to '50% 50%' (to center it on the div)
