### ISSUE TITLE
need to refresh questions here to display newly added question

### ISSUE THREAD

**Issue by dchong1999** [fecgreyjoy/FEC#82]
https://github.com/fecgreyjoy/FEC/blob/5d0cfb6679dacbc1acdcb4dd1e4060bb784dcd9b/client/src/components/Questions/QuestionModal.jsx#L40-L42

#### Description
You add a question but don't do a refresh so the newly added question will not appear

#### Screenshots (if ui based)
Not UI based

#### Files
QuestionModal.jsx > submitQuestion

#### To Reproduce
N/A

#### Tasks (optional)
Include specific tasks in the order they need to be done in. Include links to specific lines of code where the task should happen at.
- [ ] Create a refresh state in Questions.jsx
- [ ] Have a UseEffect in Questions.jsx to re-render questions upon change of refresh state
- [ ] Toggle state of refresh after adding a new question

**Comment by rocknswimmer** [comment]
I only display answered questions since thats what the business docs asked for. Therefore it would be pointless to reload because I dont display unanswered questions at all.
